### PR TITLE
fix: Participants().Playing() may returned disconnected players

### LINKED ISSUE #481: Player vanishes from connected players list, but continues to be active in the game.
**Describe the bug**
This demo https://antiochia.duckdns.org/index.php/s/ciywmyfkXe9jjxg displays curious behavior for player of steam id 76561198417781255 Namely after tick 20189 player is no longer on the connected player list, however, he also dies multiple times after this time mark, including tick 136067.
                                                                       
**To Reproduce**
https://antiochia.duckdns.org/index.php/s/ciywmyfkXe9jjxg (faceit demo)

**Expected behavior**
I reckon this is likely to be an issue with reconnected players handling.

**Library version**
v4.0.0

### PR DESCRIPTION
**Pull request by akiver**
It should fix #481, #458 and this [issue](https://github.com/akiver/cs-demo-manager/issues/723) (same problem as #458).

I noticed this thing with the demo from https://github.com/akiver/cs-demo-manager/issues/723:

disco

As you can see the last player is disconnected but still visible on the scoreboard.
When this kind of disconnection happens, the player pawn entity is "invalidated" - it points to a `CBaseViewModel` instance rather than a `CCSPlayerPawn` one.
This is why in #458 and https://github.com/akiver/cs-demo-manager/issues/723 the properties don't exist and it panics.

This PR:
- Update `player.IsConnected` when the pawn entity is invalid
- Verify that `m_hPawn` is valid, otherwise it means `m_hPlayerPawn` will point to a `CBaseViewModel`

Thanks

### CODE REVIEW

File: pkg/demoinfocs/common/player.go [hunk 1]
```diff
@@ -37,6 +37,15 @@ type Player struct {
...
 func (p *Player) PlayerPawnEntity() st.Entity {
+	pawn, exists := p.Entity.PropertyValue("m_hPawn")
+	if !exists {
+		return nil
+	}
+
+	if pawn.Handle() == constants.InvalidEntityHandleSource2 {
+		return nil
+	}
+
```
Comment (akiver) [inline pkg/demoinfocs/common/player.go:48]: An other way would be:

```go
func (p *Player) PlayerPawnEntity() st.Entity {
	playerPawn, exists := p.Entity.PropertyValue("m_hPlayerPawn")
	if !exists {
		return nil
	}

	entity := p.demoInfoProvider.FindEntityByHandle(playerPawn.Handle())
	if entity != nil && entity.ServerClass().Name() == "CCSPlayerPawn" {
		return entity
	}

	return nil
}
```

**Review by markus-wa — APPROVED** [review]
