### PR TITLE
Parser: Player tracking improvements

### LINKED ISSUE #98: Unexpected player appears in a team
**Describe the bug**
Non-player persons appear on a team. Exact definition: There is a player called Zim in this dem file, which is neither connected nor team changed. I do not know where he is coming from.
**To Reproduce**
demo link: https://www.hltv.org/download/demo/47811
matchmaking page: https://www.hltv.org/matches/2331369/izako-boars-vs-havu-lantrek-2019
**Code:**
```go
package testParser

import (
    "fmt"
    "os"
    "testing"

    dem "github.com/markus-wa/demoinfocs-golang"
    p_common "github.com/markus-wa/demoinfocs-golang/common"
    events "github.com/markus-wa/demoinfocs-golang/events"
)

//TestNonExistCOnnect test non exist player situation
func TestNonExistCOnnect(t *testing.T) {
    f, err := os.Open("/home/baran/Desktop/demo_files/test_demos/izako-boars-vs-havu-inferno.dem")
    if err != nil {
        panic(err)
    }
    defer f.Close()

    p := dem.NewParser(f)

    // gs := p.GameState()

    p.RegisterEventHandler(func(e events.PlayerDisconnected) {
        gs := p.GameState()

        if e.Player != nil {
            fmt.Printf("Player has been disconnected: name:%s team:%s tick:%d\n", e.Player.Name, e.Player.TeamState.ClanName, gs.IngameTick())
        }
    })

    p.RegisterEventHandler(func(e events.PlayerTeamChange) {
        gs := p.GameState()
        participants := gs.Participants()
        teamTerrorist := participants.TeamMembers(p_common.TeamTerrorists)
        if e.Player != nil {
            fmt.Printf("Player team changed: name:%s old team:%d new team:%d tick:%d\n", e.Player.Name, e.OldTeam, e.NewTeam, gs.IngameTick())
            for _, t := range teamTerrorist {
                if t != nil {
                    fmt.Printf("t player name:%s team:%d\n", t.Name, t.Team)

                }
            }
        }
    })

    // p.RegisterEventHandler(func(e events.Kill) {
    //     fmt.Printf("Player killed a player: attacker: %s team:%d tick:%d\n", e.Killer.Name, e.Killer.Team, gs.IngameTick())
    //     if e.Killer != nil && reconnectedPlayerID == e.Killer.SteamID {
    //         fmt.Printf("Player killed a player: attacker: %s team:%s tick:%d\n", e.Killer.Name, e.Killer.TeamState.ClanName, gs.IngameTick())
    //     }
    // })

    p.RegisterEventHandler(func(e events.PlayerConnect) {
        gs := p.GameState()

        // teamCT := participants.TeamMembers(p_common.TeamCounterTerrorists)
        if e.Player != nil {
            fmt.Printf("Player has been connected: name:%s team:%d tick:%d\n", e.Player.Name, e.Player.Team, gs.IngameTick())

        }
    })

    // Parse to end
    err = p.ParseToEnd()
    if err != nil {
        panic(err)
    }
}
```

**Expected behavior**
No player other than expected ones.

**Library version**
v1.0.1

### PR DESCRIPTION
**Pull request by markus-wa**
- Fixes #98 
- Makes `Player.IsBot` more accurate by also checking the GUID
- ~~Adds `PlayerConnect` event for bots.~~ the change for this didn't do what I expected, it ended up sending wrong events instead.
- events: delay PlayerTeamChange until end of tick
  - team IDs of other players changing teams in the same tick might not have changed yet
  - player entities might not have been re-created yet after a reconnect

Depends on #94

### CODE REVIEW

**Comment by markus-wa** [comment]
cc @quancore

**Comment by quancore** [comment]
It seems working for me. It mainly gives zim as a bot which is rudimental for me.

**Comment by markus-wa** [comment]
Hmm, sorry, this doesn't do what I intended. Zim shouldn't be there . . .

What exactly breaks for you now? I adjusted #94 to behave as previously - with the `Player` fields set on `PlayerConnect`.

**Comment by quancore** [comment]
> Hmm, sorry, this doesn't do what I intended. Zim shouldn't be there . . .
> 
> What exactly breaks for you now? I adjusted #94 to behave as previously - with the `Player` fields set on `PlayerConnect`.

I have written on gitter: On the issue of 99, it fixes bot players become a team member however because a player connects without a team and become unassigned, it breaks my code. Another important thing is that these unassigned players are not changing (or there is no playerteamchange event) their teams and becoming assigned to a team before a collection of events starts. I suggest you give a team on player connect if it is assigned and determined on connect event.

As I said, the main problem is unassigned players during connection.

**Comment by markus-wa** [comment]
>however because a player connects without a team and become unassigned

This is also happening on master right now.

from your pastebin on gitter (https://pastebin.com/PbJKYWn4):
```
Player has been connected: name:paTiTekhe_he❤W team:0 tick:365
Player has been connected: name:z0re1 team:0 tick:369
Player has been connected: name:nawrot team:0 tick:372
Player has been connected: name:peku -M- team:0 tick:372
Player has been connected: name:neexOr team:0 tick:375
Player has been connected: name:mattyb0b team:0 tick:385
Player has been connected: name:hoody team:0 tick:389
Player has been connected: name:LANTREK OBSERVER #1 team:0 tick:389
Player has been connected: name:Twixie team:0 tick:392
Player has been connected: name:sLowiNd_^ * sAq.fi team:0 tick:436
Player has been connected: name:tecek* team:0 tick:475
Player has been connected: name:LANTREK OBSERVER #2 team:0 tick:600
Player team changed: name:Twixie old team:0 new team:3 tick:1205
Player team changed: name:nawrot old team:0 new team:2 tick:1215
```

0 = unassigned

I'll need some code that produces different results before and after

**Comment by quancore** [comment]
Demo file: https://www.hltv.org/download/demo/47824
match page: https://www.hltv.org/matches/2331361/assassins-vs-besiktas-intel-challenge-katowice-2019
an output on the master branch: https://pastebin.com/FXy4JueN
an output on this branch (issue-98-unexpected-player): https://pastebin.com/ZfURN5WH

As you can see, players connect as unassigned which break my code because I am also keeping the record of players and registering on related teams on player connect events.

**Comment by markus-wa** [comment]
ok, can you provide me the relevant code?

also, what happens if you run the same code against https://www.hltv.org/download/demo/47557 on the master and branch respectively?

**Comment by quancore** [comment]
> ok, can you provide me the relevant code?
> 
> also, what happens if you run the same code against https://www.hltv.org/download/demo/47557 on the master and branch respectively?

Yes that is the case

> ok, can you provide me the relevant code?
> 
> also, what happens if you run the same code against https://www.hltv.org/download/demo/47557 on the master and branch respectively?

code is the same:
```
package testParser

import (
	"fmt"
	"os"
	"testing"

	dem "github.com/markus-wa/demoinfocs-golang"
	p_common "github.com/markus-wa/demoinfocs-golang/common"
	events "github.com/markus-wa/demoinfocs-golang/events"
)

//TestNonExistCOnnect test non exist player situation
func TestNonExistCOnnect(t *testing.T) {
	f, err := os.Open("/home/baran/Desktop/demo_files/working_demos/assassins-vs-besiktas-m1-cache.dem")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	p := dem.NewParser(f)

	// gs := p.GameState()

	p.RegisterEventHandler(func(e events.PlayerDisconnected) {
		gs := p.GameState()

		if e.Player != nil {
			fmt.Printf("Player has been disconnected: name:%s team:%s tick:%d\n", e.Player.Name, e.Player.TeamState.ClanName, gs.IngameTick())
		}
	})

	p.RegisterEventHandler(func(e events.PlayerTeamChange) {
		gs := p.GameState()
		participants := gs.Participants()
		teamTerrorist := participants.TeamMembers(p_common.TeamTerrorists)
		if e.Player != nil {
			fmt.Printf("Player team changed: name:%s old team:%d new team:%d tick:%d\n", e.Player.Name, e.OldTeam, e.NewTeam, gs.IngameTick())
			for _, t := range teamTerrorist {
				if t != nil {
					fmt.Printf("t player name:%s team:%d\n", t.Name, t.Team)

				}
			}
		}
	})

	// p.RegisterEventHandler(func(e events.Kill) {
	// 	fmt.Printf("Player killed a player: attacker: %s team:%d tick:%d\n", e.Killer.Name, e.Killer.Team, gs.IngameTick())
	// 	if e.Killer != nil && reconnectedPlayerID == e.Killer.SteamID {
	// 		fmt.Printf("Player killed a player: attacker: %s team:%s tick:%d\n", e.Killer.Name, e.Killer.TeamState.ClanName, gs.IngameTick())
	// 	}
	// })

	p.RegisterEventHandler(func(e events.PlayerConnect) {
		gs := p.GameState()

		// teamCT := participants.TeamMembers(p_common.TeamCounterTerrorists)
		if e.Player != nil {
			fmt.Printf("Player has been connected: name:%s team:%d tick:%d\n", e.Player.Name, e.Player.Team, gs.IngameTick())

		}
	})

	// Parse to end
	err = p.ParseToEnd()
	if err != nil {
		panic(err)
	}
}
```

output from master: https://pastebin.com/xatGQLCN
output from branch: https://pastebin.com/S0a3VdNK

**Comment by markus-wa** [comment]
Sorry, I meant https://www.hltv.org/download/demo/47811 - the match with our man, myth, legend `BOT Zim`

For me I get the following on master, take note of player `z0re1`:
```
Player has been connected: name:paTiTekhe_he❤W team:0 tick:365
Player has been connected: name:z0re1 team:0 tick:369 <-- team:0 and no 'Player team changed' until halftime is over
Player has been connected: name:peku -M- team:0 tick:372
Player has been connected: name:nawrot team:0 tick:372
Player has been connected: name:neexOr team:0 tick:375
Player has been connected: name:mattyb0b team:0 tick:385
Player has been connected: name:LANTREK OBSERVER #1 team:0 tick:389
Player has been connected: name:hoody team:0 tick:389
Player has been connected: name:Twixie team:0 tick:392
Player has been connected: name:sLowiNd_^ * sAq.fi team:0 tick:436
Player has been connected: name:tecek* team:0 tick:475
Player has been connected: name:LANTREK OBSERVER #2 team:0 tick:600
Player team changed: name:Twixie old team:0 new team:3 tick:1205
Player team changed: name:nawrot old team:0 new team:2 tick:1215
Player team changed: name:mattyb0b old team:0 new team:2 tick:1215
Player team changed: name:peku -M- old team:0 new team:3 tick:1244
Player has been disconnected: name:Wayne team:HAVU Gaming tick:1254
Player has been disconnected: name:Chad team:HAVU Gaming tick:1267
Player team changed: name:paTiTekhe_he❤W old team:0 new team:2 tick:1297
Player team changed: name:sLowiNd_^ * sAq.fi old team:0 new team:3 tick:1326
Player has been disconnected: name:Jeff team:HAVU Gaming tick:1327
Player team changed: name:hoody old team:0 new team:3 tick:1334
Player has been disconnected: name:Eric team:HAVU Gaming tick:1335
Player team changed: name:neexOr old team:0 new team:2 tick:1392
Player team changed: name:tecek* old team:0 new team:2 tick:1392
Player has been disconnected: name:Erik team:Izako Boars tick:1394
Player has been disconnected: name:Dan team:Izako Boars tick:1395
Player team changed: name:LANTREK OBSERVER #1 old team:0 new team:1 tick:1608
Player team changed: name:LANTREK OBSERVER #2 old team:0 new team:1 tick:1937
Player team changed: name:Twixie old team:3 new team:2 tick:234813
Player team changed: name:sLowiNd_^ * sAq.fi old team:3 new team:2 tick:234813
Player team changed: name:paTiTekhe_he❤W old team:2 new team:3 tick:234813
Player team changed: name:hoody old team:3 new team:2 tick:234813
Player team changed: name:peku -M- old team:3 new team:2 tick:234813
Player team changed: name:mattyb0b old team:2 new team:3 tick:234813
Player team changed: name:tecek* old team:2 new team:3 tick:234813
Player team changed: name:z0re1 old team:3 new team:2 tick:234813 <-- old team 3, but there was never a change from 0 to 3
Player team changed: name:nawrot old team:2 new team:3 tick:234813
Player team changed: name:neexOr old team:2 new team:3 tick:234813
Player has been disconnected: name:sLowiNd_^ * sAq.fi team:HAVU Gaming tick:466938
Player has been disconnected: name:paTiTekhe_he❤W team: tick:467084
Player has been disconnected: name:nawrot team: tick:467094
Player has been disconnected: name:tecek* team: tick:467420
Player has been disconnected: name:mattyb0b team: tick:469158
Player has been disconnected: name:neexOr team: tick:469338
Player has been disconnected: name:z0re1 team:Havu Gaming tick:476065
Player has been disconnected: name:peku -M- team:Havu Gaming tick:477543
Player has been disconnected: name:Twixie team:Havu Gaming tick:478200
```

So the issue that you mention already occurs on master.

I think this branch doesn't break anything, it just makes an already present issue more visible (which, in general, is a good thing).

**Comment by quancore** [comment]
https://github.com/markus-wa/demoinfocs-golang/pull/99#issuecomment-471632364

The thing I am tried to say is that on current master, it tries to get teams on connection but this branch it is not (see my example). Of course there can be some cases like your example that players are connected unassıgned on master as well. But the difference is that a player team change event has been triggered before event starts to assıgn player to a team on master whıle on this branch even if player team changes after unassıgned connection, ıt is not dispath a player change event. For me, team member should be assıgned to a team on connection if possible, otherwise should assıgned via player team change event before any event triggered.

**Comment by markus-wa** [comment]
> on current master, it tries to get teams on connection

It doesn't, the team just happens to be set at the end of the tick sometimes, but that's not something we can rely on.

> But the difference is that a player team change event has been triggered before event starts to assıgn player to a team on master

not true, see my last comment regarding `z0re1`

> For me, team member should be assıgned to a team on connection if possible

I'd say in this case it's not possible with sane code. What we do on master is essentially wrong and hacky, it doesn't fit with what's actually happening in the demo. It just happens to work out in some cases for your specific code.

>  otherwise should assıgned via player team change event before any event triggered.

Yeah, something I'm considering is dispatching a `PlayerTeamChange` on all changes of `Player.Team`, but here we're at the same discussion as we've been previously about events that aren't actually in the demo. I think in this case it could be a viable option.

I'm also considering using `player_connect` events, which is what we should probably do, but iirc this events is even less reliable.

I'll update when I make some progress

**Comment by markus-wa** [comment]
I think I've found a solution that mostly preserves the behaviour on `master` right now, see https://github.com/markus-wa/demoinfocs-golang/pull/94#issuecomment-471757040.

It doesn't solve https://github.com/markus-wa/demoinfocs-golang/pull/99#issuecomment-471632364 but I think we should target that separately anyway as it's not a regression.

Anyway, can you give this a go @quancore ?

**Comment by markus-wa** [comment]
Issue found by @quancore (via Gitter):

`PlayerConnected` events that shouldn't be there

> master logs: https://pastebin.com/r1wLauFA
> current branch: https://pastebin.com/85jNQAqm
> demo file: https://www.hltv.org/stats/matches/mapstatsid/21878/fnatic-vs-cloud9 (cbble)

**Comment by markus-wa** [comment]
@quancore I've now removed 7dc21bec363205107375b7c7a7e9fb13a0a2c708 - which had the side effect of sending out bad events in some cases.

I'm fairly confident that master and this branch now behave the same again now. But if you could verify it when you have time that'd be great.

**Comment by quancore** [comment]
> Issue found by @quancore (via Gitter):
> 
> `PlayerConnected` events that shouldn't be there
> 
> > master logs: https://pastebin.com/r1wLauFA
> > current branch: https://pastebin.com/85jNQAqm
> > demo file: https://www.hltv.org/stats/matches/mapstatsid/21878/fnatic-vs-cloud9 (cbble)

I am getting the exacly same output for this branch. Am I missing something?

**Comment by markus-wa** [comment]
Ahhh bollocks...

I think this is the issue this line, which fixes #98: https://github.com/markus-wa/demoinfocs-golang/pull/99/files#diff-65075f667d88f51e9b39f2042615f0fdR205

Now sometimes players get deleted even when they shouldn't be, so the next time we get a playerBind on that entity we send out another `PlayerConnect`

So yeah, guess I'll have to look into it again . . . Will keep you posted

File: sendtables/fake/entity.go [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+	"github.com/markus-wa/demoinfocs-golang/bitread"
+	st "github.com/markus-wa/demoinfocs-golang/sendtables"
+	"github.com/stretchr/testify/mock"
+)
+
+type Entity struct {
+	mock.Mock
+}
+
+func (e Entity) ServerClass() *st.ServerClass {
```
Comment (golangcibot) [inline sendtables/fake/entity.go]: ServerClass passes lock by value: github.com/markus-wa/demoinfocs-golang/sendtables/fake.Entity contains github.com/markus-wa/demoinfocs-golang/vendor/github.com/stretchr/testify/mock.Mock contains sync.Mutex (from `govet`)

File: sendtables/fake/entity.go [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+	return e.Called().Get(0).(*st.ServerClass)
+}
+
+func (e Entity) ID() int {
```
Comment (golangcibot) [inline sendtables/fake/entity.go]: ID passes lock by value: github.com/markus-wa/demoinfocs-golang/sendtables/fake.Entity contains github.com/markus-wa/demoinfocs-golang/vendor/github.com/stretchr/testify/mock.Mock contains sync.Mutex (from `govet`)

File: sendtables/fake/entity.go [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+	return e.Called().Int(0)
+}
+
+func (e Entity) Properties() []st.Property {
```
Comment (golangcibot) [inline sendtables/fake/entity.go]: Properties passes lock by value: github.com/markus-wa/demoinfocs-golang/sendtables/fake.Entity contains github.com/markus-wa/demoinfocs-golang/vendor/github.com/stretchr/testify/mock.Mock contains sync.Mutex (from `govet`)

File: sendtables/fake/entity.go [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+	return e.Called().Get(0).([]st.Property)
+}
+
+func (e Entity) FindProperty(name string) *st.Property {
```
Comment (golangcibot) [inline sendtables/fake/entity.go]: FindProperty passes lock by value: github.com/markus-wa/demoinfocs-golang/sendtables/fake.Entity contains github.com/markus-wa/demoinfocs-golang/vendor/github.com/stretchr/testify/mock.Mock contains sync.Mutex (from `govet`)

File: sendtables/fake/entity.go [hunk 5]
```diff
@@ -0,0 +1,62 @@
...
+	return e.Called(name).Get(0).(*st.Property)
+}
+
+func (e Entity) BindProperty(name string, variable interface{}, valueType st.PropertyValueType) {
```
Comment (golangcibot) [inline sendtables/fake/entity.go]: BindProperty passes lock by value: github.com/markus-wa/demoinfocs-golang/sendtables/fake.Entity contains github.com/markus-wa/demoinfocs-golang/vendor/github.com/stretchr/testify/mock.Mock contains sync.Mutex (from `govet`)

File: sendtables/fake/entity.go [hunk 6]
```diff
@@ -0,0 +1,62 @@
...
+	e.Called(name, variable, valueType)
+}
+
+func (e Entity) ApplyUpdate(reader *bitread.BitReader) {
```
Comment (golangcibot) [inline sendtables/fake/entity.go]: ApplyUpdate passes lock by value: github.com/markus-wa/demoinfocs-golang/sendtables/fake.Entity contains github.com/markus-wa/demoinfocs-golang/vendor/github.com/stretchr/testify/mock.Mock contains sync.Mutex (from `govet`)

File: sendtables/fake/entity.go [hunk 7]
```diff
@@ -0,0 +1,62 @@
...
+	e.Called(reader)
+}
+
+func (e Entity) Position() r3.Vector {
```
Comment (golangcibot) [inline sendtables/fake/entity.go]: Position passes lock by value: github.com/markus-wa/demoinfocs-golang/sendtables/fake.Entity contains github.com/markus-wa/demoinfocs-golang/vendor/github.com/stretchr/testify/mock.Mock contains sync.Mutex (from `govet`)

File: sendtables/fake/entity.go [hunk 8]
```diff
@@ -0,0 +1,62 @@
...
+	return e.Called().Get(0).(r3.Vector)
+}
+
+func (e Entity) OnPositionUpdate(handler func(pos r3.Vector)) {
```
Comment (golangcibot) [inline sendtables/fake/entity.go]: OnPositionUpdate passes lock by value: github.com/markus-wa/demoinfocs-golang/sendtables/fake.Entity contains github.com/markus-wa/demoinfocs-golang/vendor/github.com/stretchr/testify/mock.Mock contains sync.Mutex (from `govet`)

File: sendtables/fake/entity.go [hunk 9]
```diff
@@ -0,0 +1,62 @@
...
+	e.Called(handler)
+}
+
+func (e Entity) BindPosition(pos *r3.Vector) {
```
Comment (golangcibot) [inline sendtables/fake/entity.go]: BindPosition passes lock by value: github.com/markus-wa/demoinfocs-golang/sendtables/fake.Entity contains github.com/markus-wa/demoinfocs-golang/vendor/github.com/stretchr/testify/mock.Mock contains sync.Mutex (from `govet`)

File: sendtables/fake/entity.go [hunk 10]
```diff
@@ -0,0 +1,62 @@
...
+	e.Called(pos)
+}
+
+func (e Entity) OnDestroy(delegate func()) {
```
Comment (golangcibot) [inline sendtables/fake/entity.go]: OnDestroy passes lock by value: github.com/markus-wa/demoinfocs-golang/sendtables/fake.Entity contains github.com/markus-wa/demoinfocs-golang/vendor/github.com/stretchr/testify/mock.Mock contains sync.Mutex (from `govet`)

File: sendtables/fake/entity.go [hunk 11]
```diff
@@ -0,0 +1,62 @@
...
+	e.Called(delegate)
+}
+
+func (e Entity) Destroy() {
```
Comment (golangcibot) [inline sendtables/fake/entity.go]: Destroy passes lock by value: github.com/markus-wa/demoinfocs-golang/sendtables/fake.Entity contains github.com/markus-wa/demoinfocs-golang/vendor/github.com/stretchr/testify/mock.Mock contains sync.Mutex (from `govet`)

File: sendtables/fake/entity.go [hunk 12]
```diff
@@ -0,0 +1,62 @@
...
+	e.Called()
+}
+
+func (e Entity) OnCreateFinished(delegate func()) {
```
Comment (golangcibot) [inline sendtables/fake/entity.go]: OnCreateFinished passes lock by value: github.com/markus-wa/demoinfocs-golang/sendtables/fake.Entity contains github.com/markus-wa/demoinfocs-golang/vendor/github.com/stretchr/testify/mock.Mock contains sync.Mutex (from `govet`)

File: game_state.go [hunk 13]
```diff
@@ -206,3 +210,8 @@ func (ptcp Participants) FindByHandle(handle int) *common.Player {
 
 	return ptcp.playersByEntityID[handle&entityHandleIndexMask]
 }
+
+func (ptcp Participants) initalizeSliceFromByUserID() ([]*common.Player, map[int]*common.Player) {
+	byUserId := ptcp.ByUserID()
```
Comment (golangcibot) [inline game_state.go]: var `byUserId` should be `byUserID` (from `golint`)

File: sendtables/entity.go [hunk 14]
```diff
@@ -296,25 +298,29 @@ func (pe *Property) Value() PropertyValue {
...
+type PropertyValueType int
 
 // Possible types of property values.
 // See Property.Bind()
 const (
-	ValTypeInt propertyValueType = iota
+	ValTypeInt PropertyValueType = iota
 	ValTypeFloat32
-	ValTypeFloat64 // Like ValTypeFloat32 but with additional cast to float64
+	ValTypeFloat64  // Like ValTypeFloat32 but with additional cast to float64
```
Comment (golangcibot) [inline sendtables/entity.go]: File is not `gofmt`-ed with `-s` (from `gofmt`)

File: datatables_test.go [hunk 15]
```diff
@@ -0,0 +1,84 @@
+package demoinfocs
+
+import (
```
Comment (golangcibot) [inline datatables_test.go]: File is not `goimports`-ed (from `goimports`)

File: sendtables/fake/entity.go (hunk 1 above)
Comment (markus-wa) [reply sendtables/fake/entity.go]: Good bot!

**Comment by markus-wa** [comment]
So we're now setting `Player.Entity = nil` on entity destruction and suppressing players from `Participants` that don't have an `Entity`.

Together with delaying `PlayerTeamChange` events until the end of the tick this seems to do the trick.

We can't delete the entry from `Parser.gameState.playersByUserID` as we rely on it existing in some cases after the entity has been destroyed. I'm guessing this is on re-connects but I didn't investigate further.

@quancore If you could check this again that would be great 😄. Hopefully this is the last time, for both your and my sake. I've been getting a lot of headaches from all this 😅.

**Comment by quancore** [comment]
Regarding the update, this effects heavily the player pointers. On the master, a pointer pointing a player can be kept and be updated (I am only relaying getting the side of the player from parser) including player side. However, in this pull, a pointer is not updating and giving the old situation.

**Comment by markus-wa** [comment]
Hmm, that certainly wasn't the intention . . . I'll check

**Comment by markus-wa** [comment]
> However, in this pull, a pointer is not updating and giving the old situation. This behavior totally brokes my code.

I can't really reproduce this, can you provide me with a demo + code again @quancore?

Thanks!

**Comment by quancore** [comment]
demo file: https://www.hltv.org/stats/matches/mapstatsid/21878/fnatic-vs-cloud9 (cbble)
Her is my strategy for testing. I am getting a random player pointer and storing for further use. When a player killed, I am comparing the current team of the same player retrieved with the event and stored player pointer team. On the master, the kept pointer to the player is updating and also the team is updating for a player. However, in the branch, the kept pointer not updating and reference will become invalid.
Master output: https://pastebin.com/3nBQxmrW
branch output: https://pastebin.com/ViRAXfuc
code:
```
package testParser

import (
	"fmt"
	"os"
	"testing"

	dem "github.com/markus-wa/demoinfocs-golang"
	p_common "github.com/markus-wa/demoinfocs-golang/common"
	events "github.com/markus-wa/demoinfocs-golang/events"
)

//TestPLayerPointer test non exist player situation
func TestPLayerPointer(t *testing.T) {
	f, err := os.Open("/home/baran/Desktop/demo_files/working_demos/1941_fnatic-cloud9-g2a_de_cbble.dem")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	p := dem.NewParser(f)
	var playerPointer *p_common.Player

	// gs := p.GameState()

	p.RegisterEventHandler(func(e events.PlayerDisconnected) {
		gs := p.GameState()

		if e.Player != nil {
			fmt.Printf("Player has been disconnected: name:%s team:%s tick:%d\n", e.Player.Name, e.Player.TeamState.ClanName, gs.IngameTick())
		}
	})

	// p.RegisterEventHandler(func(e events.PlayerTeamChange) {
	// 	gs := p.GameState()
	// 	participants := gs.Participants()
	// 	teamTerrorist := participants.TeamMembers(p_common.TeamTerrorists)
	// 	if e.Player != nil {
	// 		fmt.Printf("Player team changed: name:%s old team:%d new team:%d tick:%d\n", e.Player.Name, e.OldTeam, e.NewTeam, gs.IngameTick())
	// 		for _, t := range teamTerrorist {
	// 			if t != nil {
	// 				fmt.Printf("t player name:%s team:%d\n", t.Name, t.Team)
	//
	// 			}
	// 		}
	// 	}
	// })

	p.RegisterEventHandler(func(e events.Kill) {
		gs := p.GameState()
		if e.Killer != nil && playerPointer.Name == e.Killer.Name {
			fmt.Printf("Player killed a player: attacker: %s team:%d tick:%d\n", e.Killer.Name, e.Killer.Team, gs.IngameTick())
			fmt.Printf("Killer previous team:%d current team:%d tick:%d\n", playerPointer.Team, e.Killer.Team, gs.IngameTick())

		}
	})

	p.RegisterEventHandler(func(e events.PlayerConnect) {
		gs := p.GameState()

		// teamCT := participants.TeamMembers(p_common.TeamCounterTerrorists)
		if e.Player != nil {
			fmt.Printf("Player has been connected: name:%s team:%d tick:%d\n", e.Player.Name, e.Player.Team, gs.IngameTick())
			playerPointer = e.Player
		}
	})

	// Parse to end
	err = p.ParseToEnd()
	if err != nil {
		panic(err)
	}
}
```

**Comment by markus-wa** [comment]
Very interesting, so there has actually been an old issue I just found thanks to this with `Participants.ByEntityID()`  (used for connects) getting completely out of sync with `ByUserID()` (used for looking up players for events).

Should be all fixed now.

**Comment by quancore** [comment]
I have checked new update _and it seems work for me. However, it seems that additional player field to get kill, death etc seems broken (nearly all _fields 0). And can you push current master to another branch if you merge this branch with the master? So, If I can face with a strange issue, I can test with the old master as well.

**Comment by markus-wa** [comment]
> However, it seems that additional player field to get kill, death etc seems broken (nearly all _fields 0).

Ok, will check tomorrow

> And can you push current master to another branch if you merge this branch with the master? So, If I can face with a strange issue, I can test with the old master as well.

> you can always check out any commit or tag you want, no need for a special branch 🙂

Just do a `git checkout a3164c51d27d8f6709140d21d551f801290e9593` for instance.

**Comment by markus-wa** [comment]
Here we go, I've pushed my next try. Please let me know if you're still facing issues

**Comment by quancore** [comment]
I have checked and it seems okay for the broken part.
