### PR TITLE
fix nil pointer dereference for valid demo

### LINKED ISSUE #162: runtime error when parsing demo file
**Describe the bug**
This started happening in the past 24 hours, probably related to recent CS:GO update. New demo files are causing the parser to crash. Trace:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xbc337d]

goroutine 88 [running]:
github.com/markus-wa/demoinfocs-golang.recoverFromUnexpectedEOF(...)
        /Users/mark/Projects/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.5.1/parsing.go:119
github.com/markus-wa/demoinfocs-golang.(*Parser).handlePacketEntities.func1(0xc00052c000)
        /Users/mark/Projects/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.5.1/entities.go:14 +0x131
panic(0xe65d80, 0x18f2110)
        /usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679 +0x1b2
github.com/markus-wa/demoinfocs-golang.(*Parser).bindNewPlayer(0xc00052c000, 0x11e8e60, 0xc000066ae0)
        /Users/mark/Projects/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.5.1/datatables.go:196 +0x10ad
github.com/markus-wa/demoinfocs-golang.(*Parser).bindPlayers.func1(0xc000066ae0)
        /Users/mark/Projects/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.5.1/datatables.go:166 +0x40
github.com/markus-wa/demoinfocs-golang/sendtables.(*ServerClass).newEntity(0xc0009efcc0, 0xc00018a3f0, 0x7, 0x8000000000000000)
        /Users/mark/Projects/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.5.1/sendtables/sendtables.go:120 +0x2f0
github.com/markus-wa/demoinfocs-golang/sendtables.(*SendTableParser).ReadEnterPVS(0xc00018a0e0, 0xc00018a3f0, 0x7, 0x19289a0)
        /Users/mark/Projects/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.5.1/sendtables/st_parser.go:290 +0xc8
github.com/markus-wa/demoinfocs-golang.(*Parser).handlePacketEntities(0xc00052c000, 0xc00459ce40)
        /Users/mark/Projects/go/pkg/mod/github.com/markus-wa/demoinfocs-golang@v1.5.1/entities.go:43 +0x296
reflect.Value.call(0xdfa3e0, 0xc000568040, 0x13, 0xfb1c17, 0x4, 0xc00026bf68, 0x1, 0x1, 0xc0000b2058, 0x80422c3f6e15e01, ...)
        /usr/local/Cellar/go/1.13.4/libexec/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0xdfa3e0, 0xc000568040, 0x13, 0xc00026bf68, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.13.4/libexec/src/reflect/value.go:321 +0xb4
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc00052c020, 0xf7f380, 0xc00459ce40)
        /Users/mark/Projects/go/pkg/mod/github.com/markus-wa/godispatch@v1.1.0/dispatch.go:48 +0x24f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc00052c020, 0xc0000661e0)
        /Users/mark/Projects/go/pkg/mod/github.com/markus-wa/godispatch@v1.1.0/dispatch.go:97 +0xf4
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues
        /Users/mark/Projects/go/pkg/mod/github.com/markus-wa/godispatch@v1.1.0/dispatch.go:83 +0x183
```

**To Reproduce**
Download link to an affected demo: https://www.dropbox.com/s/wom10hgr218yn3r/mrec_19_11_22_37_39.dem?dl=0

Code:
```go
p := dem.NewParser(bytes.NewReader(content))
p.RegisterEventHandler(func(e events.SayText2) {
	if len(e.Params) < 2 {
		return
	}

	duration := p.CurrentTime()
	totalSeconds := int64(math.Floor(duration.Seconds()))
	minutes := totalSeconds / 60
	seconds := totalSeconds % 60
	chatLogBuf.WriteString(
		fmt.Sprintf(
			"[%dm:%ds] %s<%s>: %s\n",
			minutes,
			seconds,
			e.Params[0],
			e.MsgName,
			e.Params[1],
		),
	)
})
if err = p.ParseToEnd(); err != nil {
	errors = append(errors, err)
}
```

**Expected behavior**
Parser shouldn't crash.

**Library version**
v1.5.1

### PR DESCRIPTION
**Pull request by markus-wa**
fixes #162

We just assume the player which cannot be found is a bot and skip it, since all human players were parsed correctly in the demo where this problem was encountered.

### CODE REVIEW

File: datatables.go [hunk 1]
```diff
@@ -189,6 +189,12 @@ func (p *Parser) bindPlayers() {
 func (p *Parser) bindNewPlayer(playerEntity st.IEntity) {
 	entityID := playerEntity.ID()
 	rp := p.rawPlayers[entityID-1]
+	if rp == nil {
```
Comment (golangcibot) [inline datatables.go]: only one cuddle assignment allowed before if statement (from `wsl`)

File: datatables.go [hunk 2]
```diff
@@ -193,21 +193,32 @@ func (p *Parser) bindNewPlayer(playerEntity st.IEntity) {
...
-			pl.SteamID = rp.xuid
-			pl.IsBot = rp.isFakePlayer || rp.guid == "BOT"
-			pl.UserID = rp.userID
+			pl.Name = "unknown"
+			pl.IsUnknown = true
 		}
 	}
 	p.gameState.playersByEntityID[entityID] = pl
-	p.gameState.playersByUserID[rp.userID] = pl
+	if rp != nil {
```
Comment (golangcibot) [inline datatables.go]: only one cuddle assignment allowed before if statement (from `wsl`)

File: parser.go [hunk 3]
```diff
@@ -280,6 +280,7 @@ func (p demoInfoProvider) IngameTick() int {
 }
 
 func (p demoInfoProvider) TickRate() float64 {
+	// TODO: read tickRate from CVARs as fallback
```
Comment (golangcibot) [inline parser.go]: parser.go:283: Line contains TODO/BUG/FIXME: "TODO: read tickRate from CVARs as fallba..." (from `godox`)
