### PR TITLE
events: fix ItemPickup, ItemEquip & ItemRemove UniqueID() issue

### LINKED ISSUE #119: Weapon unique id consistency
**Describe the bug**
Currently, I am trying to store all dropped and picked up weapon items for a given round. The problem is that unique ids of weapons that already dropped and picked up never matched. As far as I understand, weapon unique ids have been created with a weapon entity in item drop and item pickup events again and again.
**To Reproduce**
Any demo file.
**Expected behavior**
The parser should give the same unique id for the same weapon. For Example, if a player dropped a weapon and then other player picked up this weapon, itemdrop and itempickup events should serve with same weapon entity with the same unique id.

### PR DESCRIPTION
**Pull request by markus-wa**
fixes #119

### CODE REVIEW

File: game_events.go [hunk 1]
```diff
@@ -481,33 +481,36 @@ func (geh gameEventHandler) bombBegindefuse(desc *msg.CSVCMsg_GameEventListDescr
...
+		Player:    player,
+		Weapon:    *weapon,
+		WeaponPtr: weapon,
 	})
 }
 
 func (geh gameEventHandler) itemPickup(desc *msg.CSVCMsg_GameEventListDescriptorT, ge *msg.CSVCMsg_GameEvent) {
 	player, weapon := geh.itemEvent(desc, ge)
-	geh.dispatch(events.ItemPickup{
+	// Delayed becasue of #119 - Equipment.UniqueID()
```
Comment (golangcibot) [inline game_events.go]: `becasue` is a misspelling of `because` (from `misspell`)
