### PR TITLE
PlayerHurt: fixed nil WeaponInstance for some cases

### LINKED ISSUE #171: nil weapon in PlayerHurt event
**Describe the bug**
In a demo provided there is a `PlayerHurt` event which hold `nil` pointer to `Weapon` instance and `WeaponString` is also `""`. In game a player was hurt with a decoy grenade.

**To Reproduce**
https://www.hltv.org/download/demo/54175
Map 2 -- Dust 2

Code:
Conditional breakpoint at `game_events.go:633` (`getThrownGrenade`) with `geh.parser.gameState.ingameTick == 328041` as the condition.

**Expected behavior**
`Weapon` pointer pointing to decoy grenade that a player was hurt with (or at least a new `Equipment` instance holding `EqDecoy` value)

**Library version**
v1.7.0

**Additional context**
Code reaches the line commented with
`// if it's not a smoke this should never be reached`
so something definitely went wrong 😃

### PR DESCRIPTION
**Pull request by markus-wa**
fixes #171

### CODE REVIEW

**Comment by markus-wa** [comment]
@BestAwperEver could you let me know if this fixes #171? 🙂

File: datatables.go [hunk 1]
```diff
@@ -376,6 +381,15 @@ func (p *Parser) bindGrenadeProjectiles(entity *st.Entity) {
 	p.gameState.grenadeProjectiles[entityID] = proj
 
 	entity.OnCreateFinished(func() {
+		// copy the weapon so it doesn't get overwritten by a new entity in Parser.weapons
+		wepCopy := *(getPlayerWeapon(proj.Thrower, proj.Weapon))
```
Comment (golangcibot) [inline datatables.go]: SA1019: proj.Weapon is deprecated: Weapon exists for historical compatibility and should not be used. To access the weapon corresponding to his GrenadeProjectile, use the WeaponInstance.Weapon instead.  (from `staticcheck`)
